sudo: required
dist: trusty
language: node_js
node_js:
  - '8.1'
 
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

 
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install
 
script:
   - npm run test
